services:
  - type: web
    name: social-media-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://socialmedia-backend-5j7u.onrender.com
